### ISSUE TITLE
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

### ISSUE THREAD

**Issue by LinkToPast1990** [donghyeonk/match-lstm#1]
Excuse me, what is the function of this code?

```
for batch_idx, pl in enumerate(premise_len):
        h_s[pl:, batch_idx] *= 0.
```

1. I checked the output of pad_packed_sequence(h_s) and there are zeros for padding. (https://gist.github.com/HarshTrivedi/f4e7293e941b17d19058f6fb90ab0fec)

2. Also, when pl==premise_max_len, it causes "RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)"

**Comment by donghyeonk** [comment]
Hi @LMdeLiangMi,

1. You're correct. I'll delete the two lines.
2. Can I know your OS and pytorch version?

**Comment by LinkToPast1990** [comment]
Hi, @donghyeonk I am using Windows 10 64 bit and PyTorch 0.4.0.

Also, I change `premise = premise.to(self.device)` to `premise = premise.to(self.device, dtype=torch.long)` (same for hypothesis) to avoid "Eembedding error: “Expected tensor for argument #1 ‘indices’ to have scalar type Long; but got...".

**Comment by donghyeonk** [comment]
It is recommended to run the code on Ubuntu rather than Windows. And how about using pytorch 1.1.0?
