### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by LinkToPast1990** [donghyeonk/match-lstm#2]
`tr_loader, _, _ = snlidata.get_dataloaders(batch_size=32, num_workers=0, pin_memory=torch.cuda.is_available())`

if I do not set the num_workers as 0, I will get this BrokenPipeError. Does anyone have an idea about it?

**Comment by donghyeonk** [comment]
I set num_workers to 0 for testing but I didn't get the same error.

How about setting num_workers to 1?
