### ISSUE TITLE
What is the explanation of using multiprocessing? 

### ISSUE THREAD

**Issue by zihaohe123** [donghyeonk/match-lstm#4]
Hi,

I am kind of confused about the use or torch.multiprocessing. As far as my understanding, each batch is trained twice on the model. So training 10 epochs by 2 processes is essentially training 20 epochs. Is this correct? Since I've never used torch.multiprocessing, could you please give me more explanations about the use of it in your code? I'd appreciate it.

Best,
Zihao

**Comment by donghyeonk** [comment]
Hi @ZagHe568 

I think you are right if data is not allocated to each process disjointly.

Seeing the mnist hogwild code (https://github.com/pytorch/examples/blob/master/mnist_hogwild/main.py) will help you.
